### ISSUE TITLE
Support deleting individual tags

### ISSUE THREAD

**Issue by HackAttack** [burnettk/delete-docker-registry-image#1]
I would love to use this to clean up old tags, but it doesn't look like there is a way to delete individual tags, only the entire image.

**Comment by burnettk** [comment]
That's true; that's currently not supported. Let me know if you're working on a pull request. Otherwise, once we start using tags to a greater extent (sometime in the next month or so), I'll probably implement this.

**Comment by burnettk** [comment]
@HackAttack - I added this feature. I've used it, and I actually added some tests, but please do use some caution if you're deleting data in a registry that contains anything one-of-a-kind. :)
