### ISSUE TITLE
Registry with login/password

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [burnettk/delete-docker-registry-image#14]
Hi,

First of all thanks for these tools !

I setup my local registry to use a password ( see below )
Does this mean I ca not use the delete options ?

docker run -d --name registry \
-v /opt/registry:/opt/registry \
-v /home/hn/auth:/auth \
-e "REGISTRY_AUTH=htpasswd" \
-e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
-e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" \
-p 443:5000 --restart always \
--env-file /opt/registry/config/registry.env \
registry:2

**Comment by burnettk** [comment]
You run the script from the machine where your data is stored, so as long as you have sufficient access to delete the files under /opt/registry, you should be fine regardless of the permissions you apply to people accessing your registry over http. Cool?

**Comment by jhmnieuwenhuis** [comment]
You are fast !!

Thanks, your right.
The problem was not the password on the registry, but the access rights at the /opt/registry dir.

Thanks again !!

B.t.w. is Docker going to provide ways te delete repositories from local registry ?
         And I mean really delete, not unreference

Hans

**Comment by burnettk** [comment]
cool, glad that sorted it out.

yes, i think docker will have this facility at some point. parts of that implementation are complete and others are still pending, by my understanding, but there are a few too many tickets to fully keep track of it all.
