### ISSUE TITLE
Enable TLS verification

### ISSUE THREAD

**Issue by RTino** [burnettk/delete-docker-registry-image#18]
Since the script complains about missing TLS verification: Do you have any plans ideas on how to enable verfication ( i noticed that you explicitly turned verification off in requests lib).
`/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html`
As suggested by urllib3 there are some ways to achieve this.
=> Instead of forking this repo and implement this on our own, i thought maybe we find a solution with upstream (here) ;-)

**Comment by burnettk** [comment]
Hi @RTino ,

You're using the clean_old_versions.py script, cool. Can you submit a pull request to make it verify requests if the registry_url param starts with https? Or maybe add add a --no-ssl-verify option to the clean_old_versions.py script and respect that. I don't use that script myself and unfortunately there are no tests for it, so be careful. :)

Thanks!

**Comment by RTino** [comment]
Hey,
thanks for your quick reply. Yes we are using the mentioned script. 
As https://urllib3.readthedocs.org/en/latest/security.html points out, there are quite a few way, i just wanted to ask you if you have any preferences here, since depending on the variant we implement, it uses different root-certificates/certificate-stores.
=> If you do not prefer a single solution, i'll just implement one version, which works best for me/our company ;-)

**Comment by burnettk** [comment]
I don't think I have a preference here. Do the right thing! :)

**Comment by RTino** [comment]
See PR #20

**Comment by burnettk** [comment]
merged.
