### ISSUE TITLE
Cleanup script takes really long time with large registries

### ISSUE THREAD

**Issue by zoobab** [burnettk/delete-docker-registry-image#22]
Hi,

I have a large registry server with 500GB of images, and I try to delete one image out of there, which takes really long time compared to a small registry.

Is there a way to speed up this script for large registries?

Best,

**Comment by burnettk** [comment]
It'll get faster as you start deleting images. :) 

Sorry I didn't respond to this earlier, especially given my answer. Yes, I believe that large repos can slow things down considerably. You should have seen it when it was implemented in bash; it was way slower. :) However, I don't really think another optimization refactor is in the cards for this repo, given the docker-inc-sponsored alternatives that now exist. As such, closing.
