### ISSUE TITLE
Slow to delete a tag

### ISSUE THREAD

**Issue by canadatom** [burnettk/delete-docker-registry-image#3]
Thanks for creating this tool to allow remove images from registry. 

We have a 45gb large docker distribution v2 registry and delete a tag takes about 5 mins, this particular image only has about 150 tags. 

Is anyone else also experiencing the similar performance issue?

**Comment by burnettk** [comment]
I could totally believe a delete operation taking that amount of time. We used to have more repos, and that made the script much slower. For what it's worth, I now use the script to delete tags on a 100GB registry with repos that have up to 250 tags, and I just did a tag delete in a large repo in 25 seconds.
