### ISSUE TITLE
KeyError: 'repositories'

### ISSUE THREAD

**Issue by l0bster** [burnettk/delete-docker-registry-image#30]
Hey there,

i'm getting this error when running against a remote registry (version 2.5.1).

```
Traceback (most recent call last):
  File "clean_old_versions.py", line 182, in <module>
    main()
  File "clean_old_versions.py", line 114, in main
    repositories = response.json()["repositories"]
KeyError: 'repositories'

```

Maybe you can point me the right way?

This is my call:
python2.7 clean_old_versions.py --image '^testdummy/*' --include '^feature-*' -l 2 --registry-url https://fancy.url:8080 -U 'xxxx' -P 'yyyy' --dry-run --no_check_certificate

Regards

**Comment by burnettk** [comment]
alas, you can't run it against a remote registry. you've gotta run the script from the box where the data is siting. does that clarify?

**Comment by l0bster** [comment]
hey, i'll give it a try, thanks :) 👍
