### ISSUE TITLE
Use docker api instead of crawling the filesystem

### ISSUE THREAD

**Issue by theonlydoo** [burnettk/delete-docker-registry-image#31]
Maybe it'd be a bit lighter with a huge registry, and the registry's API is quite well documented : 

https://docs.docker.com/registry/spec/api/

**Comment by scottcarey** [comment]
Not possible for many use cases.  For example, it is not possible via that API to ask what all the manifests are.  You can ask about all of the tags, but any content with a manifest but no tag is invisible, yet eats up disk space.

**Comment by burnettk** [comment]
it doesn't sound like this is possible given the current registry API. feel free to re-open if you think the open ticket would be valuable for others, but i'm inclined to close since i'm unlikely to work on this.
