### ISSUE TITLE
Delete orphan manifests and content

### ISSUE THREAD

**Issue by scottcarey** [burnettk/delete-docker-registry-image#33]
I would like to delete all unreferenced manifests -- those without a tag.

90% of my disk space is eaten up by such things, because the continuous build system pushes artifacts to the `latest` tag (continuous delivery).  This means that stale content has no tag at all, and no way to delete it by tag name.  The GC feature in the repo is useless as well, as it does not consider such content an orphan.

**Comment by scottcarey** [comment]
Oh, I see it uses the REST api, which  makes this impossible.  Nevermind.

**Comment by sasavilic** [comment]
@scottcarey, Why REST api makes it impossible? You could still have additional API for purging unused manifests. I would really like to see this issue resolved, not closed.

**Comment by scottcarey** [comment]
@sasavilic Because there is no way to query the REST api to locate manifests without a tag.

The best I could do is to run the gc, and parse the stdout to collect all the manifests, then compare to what manifests tags point to.  Alternatively, one can crawl the file system offline.

Its awful.
