### ISSUE TITLE
execute 'delete_docker_registry_image --image imageName' ,nothing hint

### ISSUE THREAD

**Issue by akina-he** [burnettk/delete-docker-registry-image#38]
I has executed 'delete_docker_registry_image --image imageName' ,but  nothing hint,
The image in folder ‘docker/registry/v2/repositories’ has been removed.
Is this success?

**Comment by burnettk** [comment]
You are commenting on the lack of output? That is by design. You can make it more talkative with `--verbose` and of you can run it without it actually making any changes with `--dry-run` to see what will happen. Hope this helps.
